---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-ad-credentials
  namespace: auth-services
spec:
  encryptedData:
    SAMBA_ADMIN_PASSWORD: AgB6MVmjFQtMgvUdmAPzZ1+OFk8jljSzuK8cw6F6n5k1pe8S0ZmhCJ5zNAFsq+52JornXz+Na7ZTPPjShEZKOLvkYgzCFENjLdQBHiVrRRCqSrZD+z6D8zwOgUo7DwFe6PwExMotlWIpAw0wNBvc0npp8Vz0szyUiLNhWIeJpISeMze4u7rdhqKjTE59iQNTmEfUkZAtrRGkQxm0xfoAVhvSpzbhuKdKqkPv7M9agqCFsAGXODTgemqqo4ufz8jS/DpbHmtfo7twWeY4nLluGB0dg0nK2/An6yeRvy8iIphvM6zsGWQQd8KylufJ9P2qkQBSADHMJ/f3OM9AQisW8zlea5CQMIbQ7V5IucOlCZYuXzN5kV6BkIBlB+iM6KQ7d8Z6kQtVcHd2Czt+F3WzexwMDVQ3FpR+UeEfknW9S5Gzz77Gqu4kN+XOvODEjLdXt+CJVdWxevJq11wDLa7DRnaeE0pD8AoSVZsIB63Crao/Hf/LHWD2Y54rfrNN6WluztwsyNIeCb0TSQqtsiKI08OUxL9QK+aQa8ClUNcioqg7k9dr5wAaf3MpFdmfF8QW2Eso6JA0tZssVjY8vNkxLa+ZBEdJEglF0PSpoS0sym1SlfYBQCLWlvshrqaGGyFo6+tnZk7GFXVH8l/dML5SifWNqKn1p4B13gWaUHQo++QTy0Su2zzOaYQp0rgcNchtLOx0ODsQzlX5ASn2cLFi5zevIdkh7qNI94VzoQ==
  template:
    metadata:
      name: samba-ad-credentials
      namespace: auth-services
    type: Opaque
