---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: c3-credentials
  namespace: confluent
spec:
  encryptedData:
    basic.txt: AgCA7W6VjFZXFWCe/zBT2kyZSceXRj2MwCXQF0fNbaKwWQCCs9xvvYTRf8FBE4obCkv9w6D2NmHEuDl+E9KPcJHQMubb6Vwrq1qi7hdjswNE/Bf+vzXqQBUKQUpkLgjaSZltoMlf49giBuq5vaTY/m6ln5d/YqGC4fEaEaorN5JzrzeNfCYBPRRH5oK0EmF5lF6bSaCyKMBWkKfQ345rzdftE+ZEKb3dM+AHFMZ9gfLMliG4M1L6nlm7L2AKvaA7KXpTdgITpczlO+r0QTMvF4aodofWJdcArksCXJjn4/s/1+C8A6EFL1DWLZnKqMkn1V6audJtbDLpOqn0fmM/EzPEtrFui34MySsr5PxgCXTgO0l5310L+emHT+2yypL2Naxy1M0Put240ZfNDCVxyt7YgytBcgD2RfXXzqmkl9/dx8D7lLg2O/7mmwt4KGYsUQ0jVDrhlxzc5bxPOFcWwvIwgp+BheGNkXlri0U33IZSytK1RJXyqhbZAtdBmlh5DKeyntBTJtWT7heCjoB+w+u0wbZDrEIPZc6WZ/aVfr28wtbAdan4WFfUdiOvKijK/0tZ+R3wjUNkkzTAuaz48Wx5ROhPgPhp0QvK+Z7irFhIMMIJahpI95l+cLD1LApyvS2Z/986nuNIA00J5VglNy3nJcFXHcmC31NJi9tLtez6ckIiQF7ncwPkkioll2/t9vVD2sYb+ZED/qo463dC0OcfFRp5GynIhGksl4mIvEAv9aD8L5Uw62sP70d7
  template:
    metadata:
      name: c3-credentials
      namespace: confluent
    type: Opaque
