---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: c3-credentials
  namespace: confluent
spec:
  encryptedData:
    bearer.txt: AgAerdat38kk5gbdEHbgKbAETf8KAb0RM6o37RMNSzJ3J15VPMEeMSIyNejc6yhnL9YFziyx8fJnqAAPeQuJKU0PhIOf0T0Kv/EUDTxzvJc20TpHGy6dnvHYVctZ89S4Ac2X1rj/+aDb5IZyAKwR+mDlvfyJctLy4JhZCXyEoLZSwEwd/z1nuCn33uVmb4/k8uEQ5kJkSZjxlzek68RN6toDJnEpeaRf79GGo0hZMock+1RAsO6xjeido3/mVXjCRHMFPs4VsOs9wnCisUvb7EyaOuG8q0g/Y0h7KGoyDHOmUzkpeWHVPJgN51AZX/ucad6VftMIAUsEjWksdX9NpqGn9Hc47WeY3mjhCUYhQljtE+bkpVWvo7em/OVFSxoaLIjUYFSTQOYqwAXqYZ5wvdXzRVRrvsMi+tEyVeI0H/MJQM2zKJbwCMl0S00GgOaMkO7OmCzybMI/5f8kKhI7EaIvsEUkfQxiQL4TszwpwJblvk+Wd8Q1Ryu7ilac1ONts6D9qjExES55zId7rTodo4/5K0cx8sU/RCQkLvDJhcyqJLY6XZ7okxDTEWGtN06tNjjtOSnYmjLftZZN5rhvQA3/gexCMCtHd4NFhK3PkZpUKg8OP9fKUDORR7q2eLISwpTala1JxyR0VjKfm90c39wRTgJRR+bk+xI35SeMtfJBzJkiNI3wkVLD/hp/gt6co4QSwjuxBmRyvmXIiImQs3mHPPoDr3sRJ1EpLKhXqP5pmjO2G4Wr1HXnJPln
  template:
    metadata:
      name: c3-credentials
      namespace: confluent
    type: Opaque
