---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: connect-keytab
  namespace: confluent
spec:
  encryptedData:
    connect.keytab: AgAxyJhWptBTw7Pnh7/QdcSKrJkfC4Jw6UeMJyBGyODJavg59Onbmi29RQmWfUtI/jcWy6dDFfitfo0jRBWsFQwf0YNdLAYDfVJ2TQJwuH/8xyFTgRAnn6Sy4P3jFYMtK3j52iDs8rpVo2qwygNwmW1s6a72kdc6lZocEiHVd74RMhU+WRjL7/ezemI+Yv7Z0qPbdj1INF+UtaWcC8iU6EDZTYfpJGD/5112Ek5BIt5s4/lIi9AqU9tAE2Qv2uAQkIRROvHfKb7v1OGyUG4o5OhDJpl+tTMT16DSiOAxdt/A1V/t/Bxdv9UHFJP1PQHDmgl142xs0wKhSTbpm9T76tiSSeeInTAqvlTMLXklU2L6uKBu8aGECF4Xh1CocTs/B4MlG62uHyf9WeTfeFcCgQrranDV1x8cDzpx0sEpIjHNl7zxKxibnJKqRzxnhIy4toISZpMEEwNDKgEhEXHcT0viKnT14vtM+MrrWTwgRstv+6mKqgrMBvVXf9MfaFK7XojQsIB9GWeNMdfYtpLXtJ3StsrCWkhxeTqDooNliDrc2ecGHqF0SN65tIRM/b8aezz6kcmAOzSBDRiC3HuoRSykOS+BPUu4qgwHu04F6AfEsLemEEi238wxxFO3U6UgE9WzkpdH3B4ceBrOHvombmjUvUJ4fuzMIZj/Pfl8mok0mAbh40gjr6bVB/7CG8ts0yM=
  template:
    metadata:
      name: connect-keytab
      namespace: confluent
    type: Opaque
