---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: connect-keytab
  namespace: confluent
spec:
  encryptedData:
    connect.keytab: AgBBqqZUKg6AybeCv0b0eS1QAbzCfLbXwY1iPvHhBE7jZz2hCV6thLDPzCAf3PWnx0falRHAdg2n9mV81xAjbNrWc3VbBg8pn8uPtmq82TnQ+nmHj0tWgt1On9XIx3i+cNIToT4Hrt9qMXUPNoA9dOSxWn6pnb8VwHMOmwBKni208OpXo3pfbYVHmh7uEFE9wWEaavg0FAnXbuO1LnLp0jM3toLxFMNPsU7CSuMdwq6a0bOPtW/zv4M5DiAmrDHo5sbx7k40WPTKoIcaLU86yYAFLpyq0xlUsnJRuNefIKUhgqgikyv7pN4YKNLJsgxMKZUThEHHyXekYhXw9mTyAiyp1PzYveKbAWEzfh9YSBSPxqJM6wNlO6Y+sDRETgp9nRyYHWaNgHQLf6U4hpVVI5TcLlM/YNYayRGwzQ/o7UtWEm8v1riyDjesHaH/KtGU/piSugQJVRt9DQpNR0vHhxI3yrHYiNmvj1gSjoXXE9UzHs0evM75nVmtuTir2uI+Psw0d8g6Bs5zS8x+uPZuvKUEiuvVHBQ3inqPhKEYDAKQq81eYtVI1PdofwhxSzwnsWzRzwiGfdszmrqhUyrVWvudrBln0t8z2bLOVXOQ4Ogov35QiLT4+IoovWQMcitmgph/AgeKnP+1kAi5IAyF9L0HDX8E8ayEP5g0GWWDmwn3lbRfGHPTtnyqdiRyYvjRRnKRmyeUtt+wJoeIxmcPgleehzVk+1j/xkBKnU9EFTTuEWCfQqq/HcC2sNYYlg2LyU1BYbemmsJXVi+QLO+86QX10TsQ7uXwT41IcfxiqFKFGcIuRUOLkvv5QyLsZkDRVAtApz9Ys7bVCP2y/wUOvc97cP6UXLUrXDI3aCKEj3JWIqaeRIdWaXIIy73u3QQbKANajOeAfRckuP7I8Ie9PDuuz4F9wBIVItEsgYZ/9Yw6qpscklbg/CXCDSpyhtLhkwu63zSfQ60Fw0FPzLnyLNG0Xo2b4oDanXQRiSN0
  template:
    metadata:
      name: connect-keytab
      namespace: confluent
    type: Opaque
