---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: connect-keytab
  namespace: confluent
spec:
  encryptedData:
    connect.keytab: AgA9hk5FxonR+k8mW28ChV7FchhX3HetV0HxD//2hITbWCA20miQpnjjTtaQszfDQdb//p2A570q3IRD8qsNsqlrMb2KE9xzQtaI78Qr1R+xan3gEBqYYuHwnXyNssLGHL5wc/RhkDCmcx5kqwgak5l/k2ieVSlub1pZLphb/Vyu2YmjPwidjA4TKpJlAvBwH4aQkNJnyYAUw9dKaFCYUc1lO5Re7cHYepJLJnPwLufn8kj59ILNxiNJ+dBKhVWukHc1GA7jacKQhuiBQvUowsUVtVPyVG/x7qgQrBxkeUNE0mJ39U6sXE8hkt44Nvm44/73YqOdD9S0qUmPZTE6QR8tB/e0WRJzhjBDrRIAaYT0jkhJWT984FqMSRHjZEQBexIv7L2OO9XzW/SfYU1UBux+5R9cUB94/9OXWnbOWUCIrZIBaidQC2iAK07VA5AD+cHkI3AihYIMsjetg2lSDDyI1Riel4yyH2Z107OtwS232zKQaxbCFQ8p2P+TeqvSWVp3u4rDFO200iOWyfZxu/q+jP2PuE5u7EgjdSmgfNulyvqnMKBack2iR30RAvqaVJqtzx2B4b5Vp17ZPpf6k4v4/xQcrAVPdzuytgNv48lbto0HY1vzVGz4VrblO8fog7AibUvybcqXHBC4Fu1iu2qF2OdLWdjHg63HlWXoQ7UGzQSuUUf4w4gvppiBzBTq1er9dUyV+ku7nE5NaodKyf+Ijw4HVzCcvM9muclfxhx2M2x4fDocLWsxWZ9LZbLuJ/4zBT7nzfs+UaRmWs0iGLzbDYfCihjP1IW8vWQiXCUbRe8kH4LpxcCkWdLvJsbBygyWPqUL/Zh6ISLCPgK9ySv3kDPQSp0XEzDdvbFNxhy2RSu+B2pXGkCxBKuStCRZY+35EDiliSOgwl62HY1A2MscwJ0eo/USAS5zf97R/8ztwt3W7V4ufhlVbxLyjsOtjaSVQH08mybT6yzk7mAsOgXMZvRkz5QPSsAOdzc2+zBsW530T7SdE+f+dJI=
  template:
    metadata:
      name: connect-keytab
      namespace: confluent
    type: Opaque
