---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-external-sasl
  namespace: confluent
spec:
  encryptedData:
    plain-users.json: AgCeRoqTF8L6fkb6JgNb4GcWsn7FjWvjzuIJcxoP85pMaY+5WSWPzTKeRK0cxqdul60ow6EsmUE8DZfCAwIVDoULm1sjKmNW5zzTUC7JyewqJi1AV0YWwMoNxDnw9I7t+WskuiYWgG3l+qQfg/f3jx1tvsDH/ZjPkBD3m+hI1ymdH1hOgMehZyiqp3ObwL8Ca36iHMZ/tSH+/cHpKv+NNiaOCjRSbIjZzRewkA+LA6fMKZQDyEOL27DVlB4ThSEU+SRqkfu0/vMT90wj1AHoRJdmkOPsQdt27gHZxJ0kUYCtOTSzB3sN2J6m/b7bj4ZrGdVtHe4qNKrG+OtXpXyMEo2seaJR6DYz9aG24Qy7znZVnGcvpEtxyVsS9ZJ6+lmRI/xSo51Tc3qSythOkFVOWsZ63mpUi4ArlI5Cs83SEwc091+pa5uNKSP+Cm8TyXdr1AVGzpdZ9MENQYMKPTbtO7/meh3gAGhpVyklxuF5JT2wfGQdQxYN+H1wXlDQeeFKgAYtP7zBv0Fpaktwt/u2GZLHstc+wZQx1ZVgU50fpy6tdIu6/wQSpV9A93gvrIG6ltt7u69HdPDz2JTUr+kllRLz6s7Uk6PzjqolDHb/iPcTl2u63wHtRsWAYcEg7+t6QreXkxysi6EYHd6t7HNBUomdSZdGOq6zUYlzGK7EEIAqvmPPJzRDbgmbgkhAEkJhLs6VW1Y2k6h8AkbdZMipNIxFFI+oAr/IWGdH4tutXZhqu89Z9z/pFfM5O9mltVeDO8/cwfQ=
    plain.txt: AgCqLtyZ2qe/+GITUKrkBn44kRyp6syS6pYWbduIKj9VorNba6vDhtlIpV2nJlI7ph/r/tvO9+DedQob50UjiDw2kR9HMTZvOl7u3mkfDAOWpzK4A5F3e84CYOOmEriEu2wnVRCyW8RtGey18AU/CkTDfTw9jJxe3TJ+KNZXQeR3s4oHYAEn6P4Zh803iMBU2zFBSi5pGoZRt58PVWKrzZzlYT6FHUXekKyOx7VqUGTOs472uv81lSjggMqOioiea4ljOqzyhO0QMsfx4+M/JSvzcy0S2yu0+TTl+a7xDspU9gMKqt9dd75wNItT0z973KmJ2wRU24QyEuWlIqeO+yKkLuvHGBZVW7bMvZ+m9u2UMQWNCg1VbnDtxnjFYbG8Yzlmvme37tQQ1PeraT2gWr0i8odWCDjsPN/p/pSHFTe7KngjCfVnh0+bsTkXAe+cfoqRhpu7rwxxJ8zIUrlm0q9HUX7BKRjLJBYIHACPgoFMhE55E9ENiUkOk9IPXhB4oODP4BcEUwkmlm2RbH3+9g5FZfNgzT43vzDlEL4xs8Uqx3T9VmVMJ7i1IYcX3+ABm/AcHOryFnqyIA+dkbaQwUgiNPX/0f5GPDbxM0f1AQW3AUxtkNWtqYFAaVlo6UGP+IbrV1Fft/wc3HtN9S1fW6uV6GgeX6oTFB4cCptsO7078oH/qsPz2seTscPfbSymf1AQUhqTHpUpttuQh+gF8y4hk4a/lo2N1YqCGKBki6nI5wE3D4F4YugiYQpFapYv+BDnkKUQz2nRiyr8
  template:
    metadata:
      name: kafka-external-sasl
      namespace: confluent
    type: Opaque
