---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-external-sasl
  namespace: confluent
spec:
  encryptedData:
    plain-users.json: AgAlPHsq4FqPUAq+zUHZtxLAWoRzw4Zfg93DkGxvLZlOHQrpkMfkdFNmwcmC9RQW/q9wYgxit6XNzVhOlOvHRRlSKAkDqnd+8G/MZb+cqicaiW8R7V5/LQeOrGmfgl8dzDkWh9x90d00S9qcOleMGfrEWKO4araLmNyRYkDYNyM/PcTQ/KiSGP8jqE2SFwR/imaJa3qkO5tB4FY2WpRsf64tbAlmsNIBeG250A6hOmBKUq+K0GbeKrqaZGCsXDqvvpcyAgvAAv7lEfuExj8IBD4Frzx8uVCZCWXaDvhRQGpWRuq7LKQ4OX7bi17SsGVpwVfE7GuUhQ5VlkSZj/c7mT13rILWITkK6wDeZfkf4KwgMc07ph8PQlcKugV8yhfjzJ1fMGLcvWk7dHjhZIuR1WAv5XWnc9sieHAR7F2Sa7LM+qN8eHRcCBtUSULCMF8i+If0pX/NvGnFcu27wYxWxQbqDMXzAvbJ1bIkZvNHKDp8tUrHun9jGz5koCoFB82jlWggbXCrxr5MZdtFmp+qc+Hzq5SfzhjaoWrc4xuY6pjJg1LvzQX/BnGeUWRY+aFD9LhgZyArECZuvO5j6D4yQG4x0jnUnwAvRq50jOE9kZyS2CQTGXh6cJKlB31NEsvOXWj3ar9znREpt0/YCNBokzQccOF/+lSkCTt92Z7BpLBAzWX4gJM7e1ZE3oe509euJDUYcapBv9Idj608wkDVeb1LLjcAX52TfoPmzU66tGbGmY7o47L3/Ov2YMwmClhTl0vU2OM=
    plain.txt: AgBVnquz75SN0oPbfWYZ78SMvo64i9GbLQjiywLkKOTVNbXCqw8v+QkLXpx2vpuqiyGAPPKjRo5FGW6Z4/nKCYCTzThxQmypIauDKofMOM1pC1x0sqTE90gIvY6RaKg37qcALmXw7CRTDFlgsoMS+uZHxpGsVZ1bahQWB315udZ/5E3xPx91enkeizSr4pLWnOZY8eZrX2B1W1yK7DzAd8K2KAHp4kmv0RM6j6aLlW1eWThkzFflCsc9YgXetrSd/rhtl+LUJ0VXRct+nENg5a4N+GWPy1wL8oay05IL3fjxepzYIcKtXeh+hotxN6UOwHSP5K2BAXUvtpNBlQEVr9k1D1xlR2wsT783TdxkSt4YRbo/zIgz7iHJAkuST2lPysHiwj5IImbO9MMZRXOhaBYipUXi76DbneKB2+Pny/xeiTT7ced4tmNYhqGTbdXnJc9vPWzrCPlPYEIqSQANBrjNQaFHUeH3ihZLfAmYejQgKdouJZvyAzoPlug7fK9I+9YgFkf/PH1WNGLzPyti5kxsgzCQJzG67UJCIQ9RyMMoO2XeYj7DUxU5sIpcV9QfkGphf+3FvAK4UJKdst7Qm2GonJmFIUG3q74JMkl8UBWpCmQh+/2sMNN1UQIyg3RNJJguNXboUgL8rftVdK4MKs65oOCmgp0HTSGCjHtMu24ra6d1YbFlxYTVBq5kLhm44hl6f7Lgd2gQBc9aKJjXSxPfTpE2MAS6kzhlwzlk97RjBBVm3mWzpq+wk7kXy6Nb6oHlHAYbIn71Cli0
  template:
    metadata:
      name: kafka-external-sasl
      namespace: confluent
    type: Opaque
