---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-external-sasl
  namespace: confluent
spec:
  encryptedData:
    plain.txt: AgB92WHTl0xBBfPfkJ53WSq9jAluYKbMZei1sIHuf7IC3Qhyh4JDOtuOLgd2DSAKCQFCVoQuT6OGS2Jh1J2EkzDumHeNdx1CGFZ91u5zGfza9OTG7imwxNu5ZGho50ynmCWGzGvvxXFDototnPoa8BIX6JaZhrKglfK+UVCTDoAjsc9HXha/azLvBDYCNL0GMNCzF0xPTTYm7wkguJs0sjdmioBRxgDXIk8/1JgkUemoQWtU+UMvDa0VIqz3r4hbLxxNURrWXoOBDf9yYOCmP25OgRu7z7M62wIlfrhUmRPYfUWtV1su7rVeTg1qRbZFkH3BP+l3ctRGmO5ZRK0VXxJw6a8jS6HpHBO/KKwkpCOJCTRuEGkK/KUOb+Ug4Hw/lXOouYVsrPHuBw7rgQtgN/dQb9PjogsmneP6B0lm5dcdkM+R74VObFqnPr/Z+3J+hWNOWaV/J+KUTed6tf+9RHpeyesa7sSrtbb7H9rsfwxqxaA4OET/v/va4ANaByPnsnY028+z9ShRY2G7SHpuj/+m8VrwFOG1QgkF5jywrb3GcuOINdg3YqN+HEvW+Qms5YYPbyDDylGRFPW3DWzMk4zqcn2YB5zy4NgyWNoosem+7fBTE+QowR/40MdtkXbw8koUexA19ml83SpqfD3cy7GZ97NjNKv3RzLte9fp4AqG2zBi3o36aczRNsubvhnR+iubQ/hYL8YjuproZHVbW1pbQmgECLLIo/K3fvW4zplEPfilC6foHFtxJeMvCtakTeV3tIZfFXm+Bqg7
  template:
    metadata:
      name: kafka-external-sasl
      namespace: confluent
    type: Opaque
