apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sqlserver-rbac.yaml
  - sqlserver-credentials-sealed.yaml
  - sqlserver-keytab-sealed.yaml
  - sqlserver-krb5-configmap.yaml
  - sqlserver-init-configmap.yaml
  - sqlserver-deployment.yaml
