---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sqlserver-credentials
  namespace: sqlserver
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgB9jBBOO04mHaYPd2bTxeHf/wpJHQddaPNkmB0oFBSfBxZJSy+DRrCHmRWz4NcunLsQKyZpTEbLl0WmMtdgbFm885gdtal8RLP0/LeBS1cG/bctOCF/hv08om6iQdvD0fHMOCFvNWG97uj2MAUcl4rBrwoN8gN3RAhslqsOZFrW3OjgvqNjJ/eIxllwBv3j9fe3rV19bYVlOmg6hjvUsDIG3OHSICB8mPlofWIlfPYsLfehaLzmRtKWFMFf6K6P8NJec1uXqtWbKjtFjl73kaBSoE32Nw3pRdTtijELWx0iTfKGqyOLZX2z59589UJXE4liPbwepYOd0eCEC2oXT8uHOOtaurpJJW28b/kBfw0itU0SPH7VuNyXcQT4cS2JUEp0GVWySlkO1zdhzK0wfr7YJ7ZqaCXtYfgl1SEqa02vO9Wjy2g7b5Nawq3TB3Zyl8ZffTjOxDVVLOIrtVc9N2TynR+YenUkS9LhhdCVxLlITdUQREWxnT3m1Nfh+b+mObzsCxl5RAcHuvnaabZalJhlAZhmDq7BUjUTyA2pAQhsvbpghokbVqqs5fzbP621wk8QpfR4+BO21fBpCLDTAyiZDk+OE9KeXrajSJSQqxLnm8HDbYd2z4EXnkJwMGax4ciznSOEHUkwK/GoxAojAvd63CYZ39ObplfJ7gQsYbGniAuWaQBsprxQQfwgA29Vg5C9xZyL+L7C54RTnrSSv5dGkTlXSHcgJhY=
  template:
    metadata:
      name: sqlserver-credentials
      namespace: sqlserver
    type: Opaque
