---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sqlserver-keytab
  namespace: sqlserver
spec:
  encryptedData:
    mssql.keytab: AgBQ8c9xn2IHZ2JXCkkbFieBDjadvGMTyIpTWHk6P6fmGT9BDxhk7zKs/4Pfk3MZGxAadH2yNtFsR6BzcoHh/gI+jJP1BmSQltY6Gpj9yQxXlho8hGax9boDxRqM3hT/63CgILB3kCqR5u6O+p13c/ftv+MX0fQyjXRT6LO59yijHouO/gdAeQrHAQkiCjACNPTL8LWAfxSKZCiyqO67rGO8c4+99OeTHyFqeF1S2XjgfznzMTmcdisxlDC6dPHBoPaXj+4jr+xhJjDB/Z6dPQgJck7Ec0cNra96XbHIgXHhbj75CaYXwV4kbQKTIe1F9+MVprmZvFcrFkXhnUenLnAHxNR+bpcBN1NLIAzLlaux5sJq5LSoTJGPZnWcwd/vynZubQRl16ae80HrAGqHzno2bqzmpbwKoECPJ/vLxvWHjckjsVIWs8lnLnwFlkXPK5Iqvw+CPyi4FEW7ofOtZT1UFmfy0tgI8206QIxCzykSoS1DWh7QO92WSQaqKs4Oq7tNo8I1zLSglr1hktfcmxv6DcApvTsFbYd3oGGLoYlqNLci3gg73e3nUgcbKnk/NNi2pi+bu/4wl/3Uv9j+UcbPSEsTF4ws6F5QmOQrrbT8iIsHr7nfT/bj1xNdHOQzQq9rLTN4Agixm0K6b1hA8Ux/tObHYVFXb6T6obryczK/N8PK3weq55PpJ8lZuw9tSkiBD1AAUXdz1R7sAc+40TwLdr6ctiXRipQpNkZAAZHfTj0kx4/CsZc2KUdmgN8XOdJoPDYhvrWWv6qEiWeeIUvpwyIkr9g93deA47y9axoWn+ok1+TLww0TZOcudXxnt9B5L9pbtKhv/CwZo8AxpD7pXECw7p0+KeStb05OELSXoxmKzRCMrgal07qfGo1DHek6elfY9+hrHFgjF+WY5hJP6Jka2NUF4GS8JFOED54i9zPgHy4ljZmzPTl368OslWjIf6Qg/ZB6rES+pC3HhKlVIU256x6nrOBpBWudFyDungAd61jEVQoD6nah4Q==
  template:
    metadata:
      name: sqlserver-keytab
      namespace: sqlserver
    type: Opaque
