---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAylfZMg7SEYVNaPPIMiQpdXrUW5729s4YbrXiJifEEkMGkx/5zryeJu57kPoDAlEpSzRM9/5BTv0vQQAGA059OskXXOCtM2cqeTDzimHLF7BQMKAG94M9Ss1R1Elgyr4pRKc/9Jc+1FKxXxLCLcBiVcD1TvE9P1fkg9WWTUup1rxc0HfkOrKZvNTZ8BueklJ8JkxvmaWEj3DCWTC3DFeKu85PqqOkVmqj3YSyd86dXwKSgW9M13k3vmDTetqnVyh7q5X5DwojaB8Q+3ixbboK9POttoPPDIyobP/F9xlXWfEJRGjSTyNxEg3XTlbtuk1bBWe5j4IU/LW4uYhMBid0AKsDUJOtJ9sRFSBMMqNHI14sgm7r7YuVQzFni1obP7AlxHxSH1fNKc55wku/FR1YfVYNhzhWfW4l3LdIysNH4F9/NYsfr3MuVNQX3Z7LHYQs883u65351LfhHV6ekL8PQoCJGY+gFDSSgcZ62N42eIatqcahTtLKPTmnBaF3Sdt5KP06e1/HKec16QjSe7uUjL8V9C8lAR4RvOGtL8SuDRCqe1nAnLkzjNH9Jn8NI4f4VowV1ngIpbOew/eyK6QfqwR6ko94PD+lhUjeZnVWSBMMjjH04KoGSmJ9iRhA6ws9vELrFnwbe8AdR5Ab9jiK0A6kIrrvxl5XFohVlKi8ntwYaPeuOYkqcNi5NQjEHO4anxNNuU+uRgN7CAsufioMO+be7KD91aA==
    admin-user: AgBOVq4APTnE1UmYQnLN62dhP6NN577WNhsI4LwWcXQ854LfFN5wmH5nHUsQvzB6lADH+3vP6hDqQDqZsonYQA7h+97Gdg3uFWRTL/KkTKou7VfUMhkbGYRnHuEoUDZ2r00+WcNctsUS1hp+TigiXaE9BKmzhLLKeROmYT0RaoxjmHpnBR3lKiYCeVEZlfJl67wNlqx7gvTjt+ivSx5Q0JQlLM7S/Zp/oR/OFWS30alh0wBH4AeH7Mo5joIgBdPsvXjbh9z66j7vRlrAnY2QwVBay4ivkSuNVG+ACMDzftHaCmQvVHhlOf8JP7LZUIn5Mfh3vyK29H2g++DbdI3PlfLmR0likVTqGf42FQhIH4SCoZ29lDHjEJ5SVEWhvUDY2Isog0K1+X6C3Gx+CUyuLRG5Wb1oWnmilYG21kfkSMsgOYymX3Eu5GxCqgtLibv/+FMFAMke4xF6eBtIF8CTuNcyHQK6MZDLrT8HQCN/oc/thp8O0v0aBsCTCcfDtxD+bNUQgFGTuooQCdDN41UHkNmtbRZ64FA2O4ENYKD0Vnt9qwydoPG5E6Xo4qpgxc3m8t43YeDWWt0VOIg4oUUZYQInigEkLsosDl20DZFWBsp0ENaeo9cJNUp0nQPqfmwr4BeopFO7KxiclPHrLD1N1JM3Z9wiMH3ps/MT3VqD+scy0GOdxN5WLLuEGQPArfCxSTRV/Pn8Hw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
