---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgArK+Cls3eCOlyqHuk5tkjWX0PbfGiaME8WqE4bfC9hSapNmbrLLj/eNJYWEkROcSNVX94aU8fOrKuzTKw5P7aKZEviFNeuLSsIfix++/Tq8OuDcIi0CnN1f76lC0T8eENZGO08fY7aTxiS+jY3i8960+9/e4rikSjPX97bfEjtuJLzuket3JUr1/qi+WxDOC9lB/ZIKDC5ChhDK49vvl/BUfnhslvtCFobcMUUp/3R3UJKA2I7OjmPC9rZR8EhtyQMlVf0PaTN01sCmpAfC7fY0KL53fuWU8riJ++hHIQJMa+4joT8DdBbtX+2b/EDzMThQLOzLSeutPFvr1wOuDbGyRAxIEDfZB/yaRhABqcJLgalnCxKw2lGL1jV8a7BFUBv6PCciUwzDAcCkN+GtAJnqWkrG/4Yhw8sT8zxPN8LHFtpFLIBgGCgy7otAjjgVcDOfBdNTSWXuYtjoX9XZtnQhLYvaEVVoNTnP+f5ROkPTPm0th8RmVsB0JqrPCyySLcfDmgG0c8bbunl8aQwvYgSoZC+FKLTHudVV8jPyCzMYo/xIcbiJtjKy3WjyQW7uJl6JywRMBa0qu1BmDLzx9Ef4ne92QyIjaZIZ+tPIGS2Y5meLq5YkHMZpWAMezBrx5tzqsHnKzK3qyqGDQKnbFDql9r+LWE2dhiPiK33FwIkx++3um680BGjo9SqJjZIY0UUTXQBZpiB35AieWclfQgkrVGEgNcLnA==
    admin-user: AgCmysTE10p40nxpxxJjKR20nn477R61xhC0FeLDmuFIVQYxKB0d+FO3yGLHwOk3KXZCvHkHgUddBlXHJHLtcceHfYLWkOfR9VleptETecU5wBdvHqQaPo6WrdqqX0/uQr/kgNMVHXplZMC2GIXtFvpQ3p5LpMTkCFV2RTc7AmLBCq3KYrhrzoCU4l8Z3QadD1GbZjs9Dflp1HgCcQa0EgQoeYbfgk3Ia1kBUQUtLtLNhNB8z6JqT1chBo73iVvoEADkzwFn5tk4zgcLrdygZV7drENBIlSWziABimDiCxOUbiB4Mrs47AztoTiVm/p51OpkUsgcXedx+iDP55RLHsv3PF73LTh+H3HjnY61Jxii6Zaim0ORm1ewz91ig6pyLE0kXG6W9x6ylK2an/097ks4Bom0NPVRrQoJF5pR3PaDZ2+s26dkxxIM8oLREhhlk0Iv/yYIGoV/ycTHmK8/n3nQiNDJABbkfkKFd7wG6kA+UXlhCYS9+RzqrTjQrGTZuA+O1ViMSV+iYv3yUDhj8rXhpMM3KL51cTT3Aky4d7Kx4rwZboR3yoX0mFnbv2Qr7+ErfYUkJyoV6bt2fR7oNGfCghsR96CmpcKBjXS61ePNbOBlto9RrYWzq7HJum8KBvUqn8d/o5yEra9PWpL5xd94eraW8TUm4QsvGSwM5GE04BNgDzwqMt/HQ3F4o0YBt0Y0ey1VTA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
