---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAj0nOpm9kkoefdAUl5zmvA09xPhxdJYZc2ExFZVnQ20ocHTHPkZ67kkfNsUjgdQ9hGUR7C0bnPkPy2fgLvv3lATXS7iT3v1soGZK1J22q7Z3Dkqd4/85dJKwLPqxT0MzZDACMa8eylp4XuuJT+uZsMjpcebQz1KV1pr847lNZgTVbGw54BV4ftF++gdKZEBD9RLnXXrxu0hVQ140GoF86G7VGvGkZzpwdtu4Djmn6iMnJHFVMVsCzKDIBdwtyw5nAqW0W7nj9Nr1DmmRMSKJOpijDpPjZwNl2w5n7HLuG+tDoyI+xgRlL2qKeTjVnnNkz0BFRVqNiR7/7UDRRGN51V9siyuw85P3Ov5x1YYRqPKHgc1PDUY3nPbwNNVjUbZq0YoVq7Km9wSvirZaK3TPEU1ZDgaGmdyS02Dfu5D+YrVwYGeBXWrJ9HKNYi4Kx1KmQIA+lXEl6meBAhBCZrwMHl33SUib+PnqCHX4S+qSM93qndwVXlhbOz+J2xzj9CLfaEvvJvOO78ArgtXZpnsLNl55nFxzHZuRS75KrXo/Hdvsd9w7iuLnR/RTthC3CluI/EytafajB1xcAWcESSDdPrera96iMspuMpEcPyQYh7YaKcyU6lAIWgeMUJLqs3iDwykwIN+AEzzA/5ccmf9XWHf3D868uLUnJuIEBrYCpcTKWf6WkttX2uYvcO23zYkq3SrIG2JgqcDgrHOogfjXaPcuNLLCsNJQ==
    admin-user: AgCvYmzY6zZHfmQqY5nLoU9FtAp3DwaouAPMrPhkBLJ7srk4BTk2Mq41Y7lyIwd9uFYHrOMggW2IKYP51vcSYrIcYmdGi+v1ZvU5q7gi5xiVCSzOaYKivnuces8V8NLQA3TCX/m1IZ4GHzA8kI9nvUDXRnO8sK6IA1NmW7esJSMRmaNgASuNel2APIIou2MB5nhZgOoxU89qhwgT9yGryYl5/ldzfUpntroivcwNTp/Az9SDgnSF1oGZVMZb8+bVS9oddCbsX1DXVIS8++I7j1Db2uuag5C453RoyK4/OQ8L7fvbRLZnxL6uXUb0e0UTohULmI3N2aGO1pK/zEQAzdn1QsyzO7KomjU8RLAipHORL1N/gls/V5yo29ZguQDjboxY5Bpvn9I5aI/0XJhIGjHijK0d/u8Mlwhq2/i57iWqCuxwFv/QRTPsfnIKuSByMS+N/HD/oO3zHtX3aIXVbgK97NdWsDzsh6pY9iXYhIi3IDu9Alud3hAjmy01AnMTomgn4nfDjnYXbQlxBWdzlNtfUZneebJUvvsEyLc3oEiJIdoMOgCQq+6TZGjLcDtIyfsHFr0z7rtInU9bo2qFHOeu+ZMkEJW2YCSqwlqoM/PJnXuKUqAmshwfmHWhct2Vv2k0nLbDgn4fd7fRpAtosufnf3YtHghvbOoBr1mTREg48wJH4Ke9OGfd6lySm5xL2U87UkzTWw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
