---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flink-kafka-sasl
  namespace: flink-jobs
spec:
  encryptedData:
    plain.txt: AgBK/dbsEPvcyF15UJRoL89Knysz4BJNXRaSfBvNjJzryLF0sPy2k0aQOZNJIG0eYNcHE5VBO0QJoBm5egmlHZO1kQF3GH9UxcjXtBDrF53ILGjEkGNVvSngDzzUJPTew3REGYjPvLIvSEb9A8EmUmUaVf4aBw2h+oaDATaIinL91PSY+hap8w+RidqViUhTOiJhFsBYhSNzwIFPpRcxcbo7tykx8XxL0aV1i+BZda2ZLlEAkarFwIKq9uywDjlR3coQSXKrk1p+8COLAmw4rva4h6jxG8aW2MXw0T+JxYg2QopCBhOo1YR+ldL04DhCaIMWGt5f+NaFdzgmsdAUO34GbLiyVMpYzH1+E2PYkIt1BK0HRLHlOCN1yB62ZL+BXspo00yjboG+ykpQG+0FuzFngokjzcMAvobfgxYP47tD3wqNyj0+pgTFYqCIOQEgB7OZMbx495FM01ytdDlPNzQiyRpN3ojd2FcDq0cIfyPZHjXwDwvB7qkJx8P/U3F/JyaFsFbkXHehYKoYlSQf+SjXBf48xXQtK/hwpXhEWg2AJjfr1GrxSDOx70YQLDlCmcjx4jySbuFSQUV5hCrwvtNU4PU55pQ0fnBKS3mV4oDZzSnS02zY0n0obkvIBWvO0JkneSK2iVtop+xAcdf6IEo9EY8gsPQROwIyufC9gsnBYGtky5wtBC/fC+hgPWYUYnxZJgPkurBhdxT/AyR1m1nu4I5RFd2CEJwXxgfGqHTjsxlZVsFgm+Tw8ATGlXB3WGlw/g==
  template:
    metadata:
      name: flink-kafka-sasl
      namespace: flink-jobs
    type: Opaque
