---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flink-kafka-sasl
  namespace: flink-jobs
spec:
  encryptedData:
    plain.txt: AgAfHRfT8U6OfA0CVq0Om9pKjZg0KGE+JOLUgzGx+g5kakmNvvzN/bgWnTHDJ0l3rfAJWDzORK650WGlCujXs1s13Ixy7Mj6uZUcBShsrmw+z1WTMhXpQ8wpOZ6Vj+T4e3oVz+oAI+c7YKRDDTEmn5hhXgM93csrIqE7dELhDxgDcIVYIVScmT0kmGACrb+dd3lX+uDC/l+8tJJQnn7p8clgV935mBqYGkl6LCBL3cKLSdlXqNemH1PrJJWmIPOIB5tYRdrTGyDXSKgxTa6rcTF7gKT+C3rMLnYr8nG8DvMgy55P4zt7hQnT/uzJe7JWsELquhNKbiMjRzHY6s2au01SraQxuJ1yaXkkqkq7/lr31mijRDD4olFl7631JgiDDnmS73jCRE4nLKRqR8aijKmSXdSuulq0C0iPxaeK2eOE6It/q4zfIO+ffggIqoHKdS9V1pBZBtgMXyglio/4FhBG3CGBE8L+Ni+wjkKTcz4d5WP7TcLdx+qaXG/zX1EflELuiogKe7RxuySlHfzx5QrV4aVGV36d8ixhaKmyUNkXDPZg6TS0lFrm/zy3NBdbHI5HLO4CvXjnv2cLM1jiJjsZKPH5WNsrIY7NIANyu6ZZua3+LE/yc7nH2IFLUXpxJGcsRyWYEMM4cxkn1fR7ykGihTy/uVrCnBRhEH+4IlvY9mq3eH8MTfsu93/NL2V2r4E3byA8h7uBfWua9GLNBjc/3QAlzToCeEnsTSgl9nvU9Sc8G3DZcii+AgrGRiWFOjE2iA==
  template:
    metadata:
      name: flink-kafka-sasl
      namespace: flink-jobs
    type: Opaque
