apiVersion: cmf.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: statefarm-claims-processor
  namespace: flink-jobs
spec:
  jobManager:
    resource:
      memory: 512m
      cpu: 250m
  taskManager:
    replicas: 1
    resource:
      memory: 512m
      cpu: 500m
