apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/confluent-platform
patches:
  - path: kraft-patch.yaml
  - path: kafka-patch.yaml
  - path: sr-patch.yaml
  - path: connect-patch.yaml
  - path: controlcenter-patch.yaml
images:
  - name: confluentinc/cp-server
    newTag: "8.2.2"
  - name: confluentinc/cp-schema-registry
    newTag: "8.2.2"
  - name: confluentinc/cp-server-connect
    newTag: "8.2.2"
  - name: confluentinc/cp-kafka-rest
    newTag: "8.2.2"
  - name: confluentinc/cp-enterprise-control-center-next-gen
    newTag: "2.5.0"
  - name: confluentinc/cp-enterprise-prometheus
    newTag: "2.5.0"
  - name: confluentinc/cp-enterprise-alertmanager
    newTag: "2.5.0"
  - name: confluentinc/confluent-init-container
    newTag: "3.3.0"
commonAnnotations:
  deployment-environment: local-crc
