apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/grafana-admin-sealed.yaml
  - servicemonitors/kafka-servicemonitor.yaml
  - servicemonitors/kraft-servicemonitor.yaml
  - servicemonitors/connect-servicemonitor.yaml
  - servicemonitors/schemaregistry-servicemonitor.yaml
  - servicemonitors/restproxy-servicemonitor.yaml
  - servicemonitors/controlcenter-servicemonitor.yaml
  - rules/recording-rules.yaml
  - rules/kafka-rules.yaml
  - rules/connect-rules.yaml
  - rules/infra-rules.yaml
  - grafana/dashboard-configmaps/01-platform-overview-configmap.yaml
  - grafana/dashboard-configmaps/02-kafka-platform-configmap.yaml
  - grafana/dashboard-configmaps/08-connect-platform-configmap.yaml
  - grafana/dashboard-configmaps/10-schema-registry-configmap.yaml
  - grafana/dashboard-configmaps/22-k8s-resources-configmap.yaml
  - grafana/dashboard-configmaps/23-jvm-deep-dive-configmap.yaml
