apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/grafana-admin-sealed.yaml
  - servicemonitors/kafka-servicemonitor.yaml
  - servicemonitors/kraft-servicemonitor.yaml
  - servicemonitors/connect-servicemonitor.yaml
  - servicemonitors/schemaregistry-servicemonitor.yaml
  - servicemonitors/restproxy-servicemonitor.yaml
  - servicemonitors/controlcenter-servicemonitor.yaml
  - podmonitors/flink-podmonitor.yaml
  - rules/recording-rules.yaml
  - rules/kafka-rules.yaml
  - rules/connect-rules.yaml
  - rules/infra-rules.yaml
  - grafana/dashboard-configmaps/00-cfk-platform-operations-configmap.yaml
  - grafana/dashboard-configmaps/01-platform-overview-configmap.yaml
  - grafana/dashboard-configmaps/03-streaming-workload-operations-configmap.yaml
