#!/usr/bin/env bash
# Bootstraps a fresh CRC cluster: cert-manager, sealed-secrets, platform
# RBAC/SCC/NetworkPolicies, Argo CD, and the app-of-apps root Application.
# Idempotent-ish: re-running is safe for most steps because they use
# `oc apply`, but helm installs will fail if already installed — see
# docs/runbook.md for re-run guidance.
set -euo pipefail

# --- Configuration -----------------------------------------------------
GITHUB_REPO="https://github.com/anandh88/openshift-cfk-gitops-lilly"
ARGOCD_VERSION="v2.10.0"
OCP_DOMAIN="apps-crc.testing"
CERT_MANAGER_VERSION="v1.14.0"
SEALED_SECRETS_VERSION="v2.15.0"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> Bootstrapping ${GITHUB_REPO} against domain ${OCP_DOMAIN}"

# 1. Confirm we are logged in to the cluster before touching anything.
echo "==> Step 1: Checking cluster login"
oc whoami

# 2. Create all platform namespaces up front so every later apply lands.
echo "==> Step 2: Applying namespaces"
oc apply -f base/namespaces/all-namespaces.yaml

# 3. Install cert-manager with CRDs and non-root pod security everywhere.
echo "==> Step 3: Installing cert-manager ${CERT_MANAGER_VERSION}"
helm repo add jetstack https://charts.jetstack.io --force-update
helm repo update
helm upgrade --install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version "${CERT_MANAGER_VERSION}" \
  --set installCRDs=true \
  --set global.podSecurityPolicy.enabled=false \
  --set securityContext.runAsNonRoot=true \
  --set webhook.securityContext.runAsNonRoot=true \
  --set cainjector.securityContext.runAsNonRoot=true \
  --set startupapicheck.securityContext.runAsNonRoot=true

# 4. Wait for cert-manager to actually be serving before requesting certs.
echo "==> Step 4: Waiting for cert-manager rollout"
oc rollout status deployment/cert-manager -n cert-manager --timeout=180s
oc rollout status deployment/cert-manager-webhook -n cert-manager --timeout=180s
oc rollout status deployment/cert-manager-cainjector -n cert-manager --timeout=180s

# 5. Apply the bootstrap CA chain and confirm the root issuer is ready.
echo "==> Step 5: Applying cert-manager issuers"
oc apply -f bootstrap/cert-manager-issuers.yaml
sleep 15
oc wait clusterissuer/platform-ca-issuer --for=condition=Ready --timeout=60s

# 6. Request every platform leaf certificate.
echo "==> Step 6: Applying platform certificates"
oc apply -f bootstrap/platform-certificates.yaml
sleep 30

# 7. Install sealed-secrets so real credentials never touch git in plaintext.
echo "==> Step 7: Installing sealed-secrets ${SEALED_SECRETS_VERSION}"
helm repo add sealed-secrets https://bitnami.github.io/sealed-secrets --force-update
helm repo update
helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
  --namespace kube-system \
  --version "${SEALED_SECRETS_VERSION}"
oc rollout status deployment/sealed-secrets -n kube-system --timeout=120s

# 8. Fetch the sealed-secrets controller's public cert for local sealing.
echo "==> Step 8: Fetching sealed-secrets public cert"
kubeseal --fetch-cert \
  --controller-name=sealed-secrets \
  --controller-namespace=kube-system \
  > /tmp/sealed-secrets-public-cert.pem

# 9. Real secret material is never generated by this script — point at seal-secrets.sh.
echo "==> Step 9: Run scripts/seal-secrets.sh next to generate real SealedSecret manifests"
echo "    e.g. ./scripts/seal-secrets.sh"

# 10. Platform-wide RBAC and default-deny NetworkPolicies.
# No custom SCC: every CFK CR's podTemplate.podSecurityContext omits
# runAsUser/fsGroup entirely, so OpenShift's built-in restricted-v2 SCC
# assigns UIDs from each namespace's own allocated range at admission -
# no custom SecurityContextConstraints or per-SA SCC binding needed.
echo "==> Step 10: Applying platform RBAC and NetworkPolicies"
oc apply -f bootstrap/platform-rbac.yaml
oc apply -f bootstrap/network-policies.yaml

# 12. Argo CD gets its own namespace before the install manifest is applied.
echo "==> Step 12: Creating argocd namespace"
oc apply -f bootstrap/argocd-install.yaml

# 13. Apply the upstream Argo CD install manifest for the pinned version.
# Uses the core (non-HA) manifest deliberately: the HA manifest hard-requires
# argocd-server/repo-server replicas on different hosts (podAntiAffinity
# requiredDuringScheduling on kubernetes.io/hostname) and a 3-node redis-ha
# StatefulSet + HAProxy — none of which can ever schedule on CRC's single node.
echo "==> Step 13: Installing Argo CD ${ARGOCD_VERSION}"
oc apply -n argocd -f "https://raw.githubusercontent.com/argoproj/argo-cd/${ARGOCD_VERSION}/manifests/install.yaml"

# The upstream manifest hardcodes argocd-redis's runAsUser to 999, which no
# OpenShift SCC (including confluent-platform-scc, range 1000-65534) allows.
# Without this, the redis pod never schedules - ReplicaFailure/FailedCreate -
# and repo-server silently degrades (git-sourced Applications keep working
# off cache, but any operation needing a fresh cache entry, e.g. a Helm chart
# repo source seen for the first time, fails with a redis connection error).
oc patch deployment argocd-redis -n argocd --type=json \
  -p='[{"op":"remove","path":"/spec/template/spec/securityContext/runAsUser"}]'

# 14. Wait for the core Argo CD deployments to roll out.
echo "==> Step 14: Waiting for Argo CD rollout"
oc rollout status deployment/argocd-server -n argocd --timeout=300s
oc rollout status deployment/argocd-repo-server -n argocd --timeout=300s
oc rollout status deployment/argocd-applicationset-controller -n argocd --timeout=300s
oc rollout status deployment/argocd-redis -n argocd --timeout=300s
# argocd-application-controller ships as a StatefulSet even in the core manifest, not a Deployment.
oc rollout status statefulset/argocd-application-controller -n argocd --timeout=300s

# 15. Layer on our TLS cert, tuning, RBAC and route for Argo CD.
echo "==> Step 15: Applying Argo CD TLS, config, RBAC and route"
oc apply -f bootstrap/argocd-tls-cert.yaml
oc apply -f bootstrap/argocd-config.yaml
oc apply -f bootstrap/argocd-rbac-cm.yaml
oc apply -f bootstrap/argocd-route.yaml
oc rollout restart deployment/argocd-server -n argocd
oc rollout status deployment/argocd-server -n argocd --timeout=180s

# 16. Print how to reach Argo CD and retrieve its bootstrap admin password.
echo "==> Step 16: Argo CD is reachable at:"
echo "    https://argocd-server.${OCP_DOMAIN}"
echo "    Initial admin password:"
echo "    oc extract secret/argocd-initial-admin-secret -n argocd --to=-"

# 17. Apply the app-of-apps so Argo CD takes over the rest of the platform.
echo "==> Step 17: Applying app-of-apps"
oc apply -f apps/app-of-apps.yaml -n argocd

# 18. Final summary of everything that was just stood up.
echo "==> Step 18: Bootstrap complete"
cat <<EOF

Platform bootstrap finished successfully.

  Argo CD UI:        https://argocd-server.${OCP_DOMAIN}
  Control Center:     https://controlcenter.${OCP_DOMAIN}
  Schema Registry:    https://schemaregistry.${OCP_DOMAIN}
  Kafka Connect:      https://connect.${OCP_DOMAIN}
  Kafka REST Proxy:   https://kafkarestproxy.${OCP_DOMAIN}

Next steps:
  1. ./scripts/seal-secrets.sh   # generate real SealedSecret manifests
  2. git add/commit/push the sealed secrets
  3. Watch Argo CD sync: argocd app list
  4. ./scripts/validate.sh       # full platform health check
EOF
