# TODO: replace with your GitHub username in repoURL below
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mkurre/openshift-cfk-gitops.git
    targetRevision: main
    path: overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    - group: platform.confluent.io
      kind: Kafka
      jsonPointers:
        - /status
    - group: platform.confluent.io
      kind: KRaftController
      jsonPointers:
        - /status
    - group: platform.confluent.io
      kind: SchemaRegistry
      jsonPointers:
        - /status
    - group: platform.confluent.io
      kind: Connect
      jsonPointers:
        - /status
    - group: platform.confluent.io
      kind: ControlCenter
      jsonPointers:
        - /status
    - group: platform.confluent.io
      kind: KafkaRestProxy
      jsonPointers:
        - /status
